# Token configurations

# Native ETH (special entries for different protocols)
ETH:
  address: "0x0000000000000000000000000000000000000000"  # Zero address for native ETH
  curve_address: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"  # Special address for Curve
  symbol: "ETH"
  name: "Ether"
  decimals: 18
  chain_id: 1
WETH:
  address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  symbol: "WETH"
  name: "Wrapped Ether"
  decimals: 18
  chain_id: 1

USDC:
  address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
  symbol: "USDC"
  name: "USD Coin"
  decimals: 6
  chain_id: 1

USDT:
  address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
  symbol: "USDT"
  name: "Tether USD"
  decimals: 6
  chain_id: 1

DAI:
  address: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
  symbol: "DAI"
  name: "Dai Stablecoin"
  decimals: 18
  chain_id: 1

WBTC:
  address: "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
  symbol: "WBTC"
  name: "Wrapped BTC"
  decimals: 8
  chain_id: 1

LINK:
  address: "0x514910771AF9Ca656af840dff83E8264EcF986CA"
  symbol: "LINK"
  name: "ChainLink Token"
  decimals: 18
  chain_id: 1

UNI:
  address: "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984"
  symbol: "UNI"
  name: "Uniswap"
  decimals: 18
  chain_id: 1

AAVE:
  address: "0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9"
  symbol: "AAVE"
  name: "Aave Token"
  decimals: 18
  chain_id: 1

CRV:
  address: "0xD533a949740bb3306d119CC777fa900bA034cd52"
  symbol: "CRV"
  name: "Curve DAO Token"
  decimals: 18
  chain_id: 1

CVX:
  address: "0x4e3FBD56CD56c3e72c1403e103b45Db9da5B9D2B"
  symbol: "CVX"
  name: "Convex Token"
  decimals: 18
  chain_id: 1

FRAX:
  address: "0x853d955aCEf822Db058eb8505911ED77F175b99e"
  symbol: "FRAX"
  name: "Frax"
  decimals: 18
  chain_id: 1

MKR:
  address: "0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2"
  symbol: "MKR"
  name: "Maker"
  decimals: 18
  chain_id: 1

LDO:
  address: "0x5A98FcBEA516Cf06857215779Fd812CA3beF1B32"
  symbol: "LDO"
  name: "Lido DAO Token"
  decimals: 18
  chain_id: 1

FXS:
  address: "0x3432B6A60D23Ca0dFCa7761B7ab56459D9C964D0"
  symbol: "FXS"
  name: "Frax Share"
  decimals: 18
  chain_id: 1

# Curve-specific tokens
crvUSD:
  address: "0xf939E0A03FB07F59A73314E73794Be0E57ac1b4E"
  symbol: "crvUSD"
  name: "Curve.Fi USD Stablecoin"
  decimals: 18
  chain_id: 1

TUSD:
  address: "0x0000000000085d4780B73119b644AE5ecd22b376"
  symbol: "TUSD"
  name: "TrueUSD"
  decimals: 18
  chain_id: 1

USDP:
  address: "0x8E870D67F660D95d5be530380D0eC0bd388289E1"
  symbol: "USDP"
  name: "Pax Dollar"
  decimals: 18
  chain_id: 1

GUSD:
  address: "0x056Fd409E1d7A124BD7017459dFEa2F387b6d5Cd"
  symbol: "GUSD"
  name: "Gemini Dollar"
  decimals: 2
  chain_id: 1

# Liquid Staking Tokens
stETH:
  address: "0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84"
  symbol: "stETH"
  name: "Lido Staked Ether"
  decimals: 18
  chain_id: 1